INSERT INTO app_user (name, email, password) VALUES
                                                 ('John Smith', 'john.smith@example.com', '$2a$10$examplePasswordHash1'),
                                                 ('Michael Johnson', 'michael.johnson@example.com', '$2a$10$examplePasswordHash2'),
                                                 ('David Williams', 'david.williams@example.com', '$2a$10$examplePasswordHash3'),
                                                 ('James Brown', 'james.brown@example.com', '$2a$10$examplePasswordHash4'),
                                                 ('Christopher Jones', 'christopher.jones@example.com', '$2a$10$examplePasswordHash5'),
                                                 ('Daniel Garcia', 'daniel.garcia@example.com', '$2a$10$examplePasswordHash6'),
                                                 ('Matthew Martinez', 'matthew.martinez@example.com', '$2a$10$examplePasswordHash7'),
                                                 ('Andrew Anderson', 'andrew.anderson@example.com', '$2a$10$examplePasswordHash8'),
                                                 ('Joshua Thomas', 'joshua.thomas@example.com', '$2a$10$examplePasswordHash9'),
                                                 ('Joseph White', 'joseph.white@example.com', '$2a$10$examplePasswordHash10'),
                                                 ('Brian Harris', 'brian.harris@example.com', '$2a$10$examplePasswordHash11'),
                                                 ('Justin Clark', 'justin.clark@example.com', '$2a$10$examplePasswordHash12'),
                                                 ('Ethan Lewis', 'ethan.lewis@example.com', '$2a$10$examplePasswordHash13'),
                                                 ('Kevin Walker', 'kevin.walker@example.com', '$2a$10$examplePasswordHash14'),
                                                 ('Ryan Hall', 'ryan.hall@example.com', '$2a$10$examplePasswordHash15'),
                                                 ('Brandon Young', 'brandon.young@example.com', '$2a$10$examplePasswordHash16'),
                                                 ('Nicholas King', 'nicholas.king@example.com', '$2a$10$examplePasswordHash17'),
                                                 ('Tyler Wright', 'tyler.wright@example.com', '$2a$10$examplePasswordHash18'),
                                                 ('Austin Scott', 'austin.scott@example.com', '$2a$10$examplePasswordHash19'),
                                                 ('Christian Adams', 'christian.adams@example.com', '$2a$10$examplePasswordHash20'),
                                                 ('Evan Baker', 'evan.baker@example.com', '$2a$10$examplePasswordHash21'),
                                                 ('Benjamin Mitchell', 'benjamin.mitchell@example.com', '$2a$10$examplePasswordHash22'),
                                                 ('Zachary Green', 'zachary.green@example.com', '$2a$10$examplePasswordHash23'),
                                                 ('Anthony Carter', 'anthony.carter@example.com', '$2a$10$examplePasswordHash24'),
                                                 ('Gabriel Nelson', 'gabriel.nelson@example.com', '$2a$10$examplePasswordHash25'),
                                                 ('Dylan Hill', 'dylan.hill@example.com', '$2a$10$examplePasswordHash26'),
                                                 ('Caleb Ramirez', 'caleb.ramirez@example.com', '$2a$10$examplePasswordHash27'),
                                                 ('Noah Roberts', 'noah.roberts@example.com', '$2a$10$examplePasswordHash28'),
                                                 ('Connor Phillips', 'connor.phillips@example.com', '$2a$10$examplePasswordHash29'),
                                                 ('Isaac Campbell', 'isaac.campbell@example.com', '$2a$10$examplePasswordHash30'),
                                                 ('Gavin Parker', 'gavin.parker@example.com', '$2a$10$examplePasswordHash31'),
                                                 ('Logan Evans', 'logan.evans@example.com', '$2a$10$examplePasswordHash32'),
                                                 ('Cameron Edwards', 'cameron.edwards@example.com', '$2a$10$examplePasswordHash33'),
                                                 ('Owen Collins', 'owen.collins@example.com', '$2a$10$examplePasswordHash34'),
                                                 ('Elijah Stewart', 'elijah.stewart@example.com', '$2a$10$examplePasswordHash35'),
                                                 ('Brayden Sanchez', 'brayden.sanchez@example.com', '$2a$10$examplePasswordHash36'),
                                                 ('Carter Morris', 'carter.morris@example.com', '$2a$10$examplePasswordHash37'),
                                                 ('Lucas Rogers', 'lucas.rogers@example.com', '$2a$10$examplePasswordHash38'),
                                                 ('Jason Reed', 'jason.reed@example.com', '$2a$10$examplePasswordHash39'),
                                                 ('Aaron Cook', 'aaron.cook@example.com', '$2a$10$examplePasswordHash40');


INSERT INTO user_roles (user_id, roles) VALUES
                                            (1, 'RIDER'),
                                            (2, 'RIDER'),
                                            (2, 'DRIVER'),
                                            (3, 'RIDER'),
                                            (3, 'DRIVER'),
                                            (4, 'RIDER'),
                                            (4, 'DRIVER'),
                                            (5, 'RIDER'),
                                            (5, 'DRIVER'),
                                            (6, 'RIDER'),
                                            (6, 'DRIVER'),
                                            (7, 'RIDER'),
                                            (7, 'DRIVER'),
                                            (8, 'RIDER'),
                                            (8, 'DRIVER'),
                                            (9, 'RIDER'),
                                            (9, 'DRIVER'),
                                            (10, 'RIDER'),
                                            (10, 'DRIVER'),
                                            (11, 'RIDER'),
                                            (11, 'DRIVER'),
                                            (12, 'RIDER'),
                                            (12, 'DRIVER'),
                                            (13, 'RIDER'),
                                            (13, 'DRIVER'),
                                            (14, 'RIDER'),
                                            (14, 'DRIVER'),
                                            (15, 'RIDER'),
                                            (15, 'DRIVER'),
                                            (16, 'RIDER'),
                                            (16, 'DRIVER'),
                                            (17, 'RIDER'),
                                            (17, 'DRIVER'),
                                            (18, 'RIDER'),
                                            (18, 'DRIVER'),
                                            (19, 'RIDER'),
                                            (19, 'DRIVER'),
                                            (20, 'RIDER'),
                                            (20, 'DRIVER'),
                                            (21, 'RIDER'),
                                            (21, 'DRIVER'),
                                            (22, 'RIDER'),
                                            (22, 'DRIVER'),
                                            (23, 'RIDER'),
                                            (23, 'DRIVER'),
                                            (24, 'RIDER'),
                                            (24, 'DRIVER'),
                                            (25, 'RIDER'),
                                            (25, 'DRIVER'),
                                            (26, 'RIDER'),
                                            (26, 'DRIVER'),
                                            (27, 'RIDER'),
                                            (27, 'DRIVER'),
                                            (28, 'RIDER'),
                                            (28, 'DRIVER'),
                                            (29, 'RIDER'),
                                            (29, 'DRIVER'),
                                            (30, 'RIDER'),
                                            (30, 'DRIVER'),
                                            (31, 'RIDER'),
                                            (31, 'DRIVER'),
                                            (32, 'RIDER'),
                                            (32, 'DRIVER'),
                                            (33, 'RIDER'),
                                            (33, 'DRIVER'),
                                            (34, 'RIDER'),
                                            (34, 'DRIVER'),
                                            (35, 'RIDER'),
                                            (35, 'DRIVER'),
                                            (36, 'RIDER'),
                                            (36, 'DRIVER'),
                                            (37, 'RIDER'),
                                            (37, 'DRIVER'),
                                            (38, 'RIDER'),
                                            (38, 'DRIVER'),
                                            (39, 'RIDER'),
                                            (39, 'DRIVER'),
                                            (40, 'RIDER'),
                                            (40, 'DRIVER');

INSERT INTO rider (user_id, rating) VALUES
    (1, 4.9);

INSERT INTO driver (user_id, rating, available, current_location) VALUES
                                                                          (2, 4.7, true, ST_GeomFromText('POINT(77.1025 28.7041)', 4326)),
                                                                          (3, 4.8, true, ST_GeomFromText('POINT(77.2167 28.6667)', 4326)),
                                                                          (4, 4.6, true, ST_GeomFromText('POINT(77.2273 28.6353)', 4326)),
                                                                          (5, 4.9, true, ST_GeomFromText('POINT(77.2500 28.5500)', 4326)),
                                                                          (6, 4.3, true, ST_GeomFromText('POINT(77.2000 28.6200)', 4326)),
                                                                          (7, 4.4, true, ST_GeomFromText('POINT(77.2800 28.5900)', 4326)),
                                                                          (8, 4.5, true, ST_GeomFromText('POINT(77.2600 28.6800)', 4326)),
                                                                          (9, 4.6, true, ST_GeomFromText('POINT(77.2200 28.6400)', 4326)),
                                                                          (10, 4.7, true, ST_GeomFromText('POINT(77.2700 28.6700)', 4326)),
                                                                          (11, 4.8, true, ST_GeomFromText('POINT(77.2400 28.6100)', 4326)),
                                                                          (12, 4.2, true, ST_GeomFromText('POINT(77.2300 28.6600)', 4326)),
                                                                          (13, 4.1, true, ST_GeomFromText('POINT(77.1900 28.6000)', 4326)),
                                                                          (14, 4.0, true, ST_GeomFromText('POINT(77.1800 28.6300)', 4326)),
                                                                          (15, 4.5, true, ST_GeomFromText('POINT(77.1500 28.6500)', 4326)),
                                                                          (16, 4.3, true, ST_GeomFromText('POINT(77.1200 28.6700)', 4326)),
                                                                          (17, 4.6, true, ST_GeomFromText('POINT(77.1700 28.6800)', 4326)),
                                                                          (18, 4.4, true, ST_GeomFromText('POINT(77.1400 28.6900)', 4326)),
                                                                          (19, 4.7, true, ST_GeomFromText('POINT(77.1300 28.7000)', 4326)),
                                                                          (20, 4.8, true, ST_GeomFromText('POINT(77.1100 28.7100)', 4326)),
                                                                          (21, 4.5, true, ST_GeomFromText('POINT(77.2295 28.6129)', 4326)),
                                                                          (22, 4.7, true, ST_GeomFromText('POINT(77.2285 28.6159)', 4326)),
                                                                          (23, 4.8, true, ST_GeomFromText('POINT(77.2315 28.6119)', 4326)),
                                                                          (24, 4.6, true, ST_GeomFromText('POINT(77.2325 28.6169)', 4326)),
                                                                          (25, 4.9, true, ST_GeomFromText('POINT(77.2345 28.6179)', 4326)),
                                                                          (26, 4.3, true, ST_GeomFromText('POINT(77.2355 28.6199)', 4326)),
                                                                          (27, 4.4, true, ST_GeomFromText('POINT(77.2365 28.6219)', 4326)),
                                                                          (28, 4.5, true, ST_GeomFromText('POINT(77.2375 28.6239)', 4326)),
                                                                          (29, 4.6, true, ST_GeomFromText('POINT(77.2385 28.6259)', 4326)),
                                                                          (30, 4.7, true, ST_GeomFromText('POINT(77.2395 28.6279)', 4326)),
                                                                          (31, 4.8, true, ST_GeomFromText('POINT(77.2405 28.6299)', 4326)),
                                                                          (32, 4.2, true, ST_GeomFromText('POINT(77.2415 28.6319)', 4326)),
                                                                          (33, 4.1, true, ST_GeomFromText('POINT(77.2425 28.6339)', 4326)),
                                                                          (34, 4.0, true, ST_GeomFromText('POINT(77.2435 28.6359)', 4326)),
                                                                          (35, 4.5, true, ST_GeomFromText('POINT(77.2445 28.6379)', 4326)),
                                                                          (36, 4.3, true, ST_GeomFromText('POINT(77.2455 28.6399)', 4326)),
                                                                          (37, 4.6, true, ST_GeomFromText('POINT(77.2465 28.6419)', 4326)),
                                                                          (38, 4.4, true, ST_GeomFromText('POINT(77.2475 28.6439)', 4326)),
                                                                          (39, 4.7, true, ST_GeomFromText('POINT(77.2485 28.6459)', 4326)),
                                                                          (40, 4.8, true, ST_GeomFromText('POINT(77.2495 28.6479)', 4326));

INSERT INTO wallet ( user_id, balance) VALUES
    (1, 100),
    (2,400);